apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cron-job  
spec:
# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#writing-a-cronjob-spec
#            ┌───────────── minute (0 - 59)
#            │ ┌───────────── hour (0 - 23)
#            │ │ ┌───────────── day of the month (1 - 31)
#            │ │ │ ┌───────────── month (1 - 12)
#            │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
#            │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
#            │ │ │ │ │ 
#            │ │ │ │ │
#            * * * * *
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      completions: 1 
      ttlSecondsAfterFinished: 270
      template:
        metadata:
          labels:
            color: yellow
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
                - sleep 3
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/os: linux
      

